<?php
/**
 * Created by PhpStorm.
 * User: wangzaron
 * Date: 2018/5/21
 * Time: 下午10:50
 */

namespace App\Ali\Oauth;


use Payment\ChargeContext;

class OauthChargeContext extends ChargeContext
{
    public function initCharge($channel, array $config)
    {
        if($channel === Config::ALI_USER_OAUTH){
            $this->channel = new Auth($config);
        }elseif($channel === Config::ALI_OAUTH_TOKEN){
            $this->channel = new Token($config);
        }else{
            parent::initCharge($channel, $config); // TODO: Change the autogenerated stub
        }
    }
}