<?php
/**
 * Created by PhpStorm.
 * User: wangzaron
 * Date: 2018/5/21
 * Time: 下午10:50
 */

namespace App\Ali\Oauth;


use Payment\ChargeContext;

class OauthChargeContext extends ChargeContext
{
    protected $responseData = null;

    protected $request = null;
    public function initCharge($channel, array $config)
    {
        if($channel === Config::ALI_USER_OAUTH){
            $this->channel = new Auth($config);
        }elseif($channel === Config::ALI_OAUTH_TOKEN){
            $this->channel = new Token($config);
        }else{
            parent::initCharge($channel, $config); // TODO: Change the autogenerated stub
        }
    }

    public function defaultOAuth() {
        $this->responseData = [
            'scopes' => 'auth_base',
            'state' => 'init'
        ];
        return $this;
    }

    public function charge(array $data)
    {
        $this->responseData = parent::charge($data); // TODO: Change the autogenerated stub
        return $this;
    }

    public function response() {
        return $this->responseData;
    }

    public function redirect($redirectUri) {
        $this->responseData['redirect_uri'] = $redirectUri;
        $this->responseData = $this->charge($this->responseData);
        return redirect($this->responseData);
    }

    public function setRequest($request) {
        $this->request = $request;
        return $this;
    }
}