<?php
/**
 * Created by PhpStorm.
 * User: wangzaron
 * Date: 2018/5/21
 * Time: 下午10:50
 */

namespace App\Ali\Oauth;


use Illuminate\Support\Facades\Log;
use Payment\ChargeContext;

class OauthChargeContext extends ChargeContext
{
    protected $responseData = null;

    protected $request = null;

    protected $params = [];

    protected $config = [];
    public function initCharge($channel, array $config)
    {
        $this->config = $config;
        if($channel === Config::ALI_USER_OAUTH){
            $this->channel = new Auth($config);
        }elseif($channel === Config::ALI_OAUTH_TOKEN){
            $this->channel = new Token($config);
        }elseif($channel === Config::ALI_USER_SHARE) {
            $this->channel = new User($config);
        }else {
            parent::initCharge($channel, $config); // TODO: Change the autogenerated stub
        }
    }

    public function defaultOAuth() {
        $this->params = [
            'scopes' => 'auth_base',
            'state' => 'init'
        ];
        return $this;
    }

    /**
     * @param array $data
     * @return  OauthChargeContext
     * @throws
     * */
    public function charge(array $data)
    {
        Log::info('--------- config ---------', $this->config);
        $this->responseData = parent::charge($data); // TODO: Change the autogenerated stub
        return $this;
    }

    public function getToken() {
        return $this->responseData;
    }

    public function getUser()
    {
        return $this->responseData;
    }

    public function response() {
        return $this->responseData;
    }

    public function redirect($redirectUri) {
        $this->params['redirect_uri'] = $redirectUri;
        $this->charge($this->params);
        return redirect($this->responseData);
    }

    public function with(array $parameters)
    {
        $this->responseData = $parameters;
        return $this;
    }

    public function setRequest($request) {
        $this->request = $request;
        return $this;
    }
}