<?php
/**
 * Created by PhpStorm.
 * User: wangzaron
 * Date: 2019/1/24
 * Time: 12:18 PM
 */

namespace App\Http\Requests\Merchant;


use Urameshibr\Requests\FormRequest;

class SmsLoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'mobile' => ['required', 'mobile'],
            'code' => ['required', 'verify_code']
        ];
    }

    public function messages()
    {
        return [
            'mobile.required' => '手机号码（mobile）是必须参数',
            'code.required' => '验证码（code）是必须参数',
            'mobile.mobile' => '手机号码（mobile）格式code',
            'code.verify_code' => '验证码(code)必须是6位数字'
        ];// TODO: Change the autogenerated stub
    }
}