<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/27
 * Time: 下午7:51
 */

namespace App\Routes;


use Dingo\Api\Routing\Router as DingoRouter;
use Laravel\Lumen\Routing\Router as LumenRouter;

class AuthApiRoutes extends ApiRoutes
{
    /**
     * @param LumenRouter|DingoRouter $router
     * */
    protected function subRoutes($router)
    {
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->get('/public/key', ['as' => 'user.public.key', 'uses' => 'AuthController@getPublicKey']);
        $router->get('/auth', ['as' => 'user.login', 'uses' => 'AuthController@authenticate']);
        $router->get('/logout', ['as' => 'user.logout', 'uses' => 'AuthController@logout']);
        $router->post('/register', ['as' => 'user.register', 'uses' => 'AuthController@register']);
    }
}