<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/27
 * Time: 下午7:51
 */

namespace App\Routes;


use Dingo\Api\Routing\Router;

class AuthRoutes extends Routes
{
    protected function subRoutes(Router $api)
    {
        parent::subRoutes($api); // TODO: Change the autogenerated stub
        $api->get('/auth', ['as' => 'login', 'uses' => 'AuthController@authenticate']);
        $api->get('/logout', ['as' => 'login', 'uses' => 'Auth\AuthController@logout']);
    }
}