<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/28
 * Time: 上午9:27
 */

namespace App\Routes;


use Dingo\Api\Routing\Router as DingoRouter;
use Laravel\Lumen\Routing\Router as LumenRouter;

class MiniProgramApiRoutes extends ApiRoutes
{
    /**
     * @param LumenRouter|DingoRouter $router
     * */
    public function subRoutes($router)
    {
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->post('/register/user', ['as' => 'user.register.user','uses' => 'AuthController@registerUser']);
        $router->get('/user/info', ['as' => 'user.info','uses' => 'AuthController@userInfo']);
        $router->get('/new/activity', ['as' => 'user.new.activity','uses' => 'ActivityController@newActivity']);
        $router->get('/app/access/{appid}/{appsecret}', ['as' => 'user.app.access','uses' => 'AuthController@appAccess']);
    }
}