<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/28
 * Time: 上午9:27
 */

namespace App\Routes;


use Dingo\Api\Routing\Router;

class MiniProgramRoutes extends Routes
{
    use CommonRoutes;

    public function subRoutes(Router $api)
    {
        parent::subRoutes($api); // TODO: Change the autogenerated stub
    }
}