<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/28
 * Time: 上午9:27
 */

namespace App\Routes;


use Dingo\Api\Routing\Router as DingoRouter;
use Laravel\Lumen\Routing\Router as LumenRouter;

class MiniProgramApiRoutes extends ApiRoutes
{
    /**
     * @param LumenRouter|DingoRouter $router
     * */
    public function subRoutes($router)
    {
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->post('/register/user', ['as' => 'user.register.user','uses' => 'AuthController@registerUser']);
        $router->get('/user/info', ['as' => 'user.info','uses' => 'AuthController@userInfo']);
        $router->get('/mvp/login/{code}', ['as' => 'user.mvp.login','uses' => 'AuthController@mvpLogin']);
        $router->get('/save/mobile/{code}', ['as' => 'user.save.mobile','uses' => 'AuthController@saveMobile']);
        $router->get('/new/activity', ['as' => 'user.new.activity','uses' => 'ActivityController@newActivity']);
        $router->get('/new/activity/{activityId}/merchandises', ['as' => 'user.new.activity.merchandises','uses' => 'ActivityController@newActivityMerchandises']);
        $router->get('/app/access/{appid}/{appsecret}', ['as' => 'user.app.access','uses' => 'AuthController@appAccess']);
        $router->get('/nearest/store', ['as' => 'user.nearest.store','uses' => 'ShopsController@nearestStore']);
        $router->get('/nearby/stores', ['as' => 'user.nearby.stores','uses' => 'ShopsController@nearbyStores']);
        $router->get('/categories', ['as' => 'user.categories','uses' => 'CategoriesController@categories']);
        $router->get('/categories/{id}/merchandises', ['as' => 'user.categories.merchandises','uses' => 'CategoriesController@categoriesMerchandises']);
        $router->get('/store/{id}/categories', ['as' => 'user.store.categories','uses' => 'CategoriesController@storeCategories']);
        $router->get('/store/{id}/category/{categoryid}/merchandises', ['as' => 'user.store.category.merchandise','uses' => 'CategoriesController@storeCategoryMerchandise']);
        $router->get('/user/tickets/{status}', ['as' => 'user.user.tickets','uses' => 'UserController@UserTickets']);
        $router->post('/create/order', ['as' => 'user.create.order','uses' => 'OrderController@createOrder']);
        $router->post('/add/merchandise', ['as' => 'user.add.merchandise','uses' => 'ShoppingCartController@addMerchandise']);
        $router->post('/reduce/merchandise', ['as' => 'user.reduce.merchandise','uses' => 'ShoppingCartController@reduceMerchandise']);
        $router->get('/empty/merchandise/{storeId}', ['as' => 'user.empty.merchandise','uses' => 'ShoppingCartController@emptyMerchandise']);
        $router->get('/shoppingcart/merchandises/{store_id}', ['as' => 'user.shoppingcart.merchandises','uses' => 'ShoppingCartController@shoppingCartMerchandises']);
        $router->get('/store/buffet/orders', ['as' => 'user.store.buffet.orders','uses' => 'OrderController@storeBuffetOrders']);
        $router->get('/store/send/orders', ['as' => 'user.store.send.orders','uses' => 'OrderController@storeSendOrders']);
        $router->get('/store/stock/statistics', ['as' => 'user.store.stock.statistics','uses' => 'CategoriesController@storeStockStatistics']);
        $router->put('/store/merchandise/{id}/stock', ['as' => 'user.store.merchandise.stock','uses' => 'CategoriesController@storeMerchandiseStock']);
        $router->get('/{status}/orders', ['as' => 'user.orders','uses' => 'OrderController@Orders']);
        $router->get('/store/orders/summary', ['as' => 'user.store.orders.summary','uses' => 'OrderController@storeOrdersSummary']);
        $router->get('/store/sell/statistics', ['as' => 'user.store.sell.statistics','uses' => 'ShopsController@storeSellStatistics']);
        $router->get('/store/statistics', ['as' => 'user.store.statistics','uses' => 'ShopsController@storeStatistics']);
        $router->get('/store/purchase/statistics', ['as' => 'user.store.purchase.statistics','uses' => 'PurchaseOrderController@storePurchaseStatistics']);
        $router->get('/store/code/order/merchandise/up', ['as' => 'user.store.code.order.merchandise.up','uses' => 'PurchaseOrderController@storeCodeOrderMerchandiseUp']);
        $router->get('/search/shop/merchandises/{shopId}', ['as' => 'user.search.shop.merchandises','uses' => 'ShopsController@searchShopMerchandises']);
        $router->get('/reserve/search/merchandises', ['as' => 'user.reserve.search.','uses' => 'CategoriesController@reserveSearchMerchandises']);
    }
}