<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/28
 * Time: 上午9:27
 */

namespace App\Routes;


use Dingo\Api\Routing\Router as DingoRouter;
use Laravel\Lumen\Routing\Router as LumenRouter;

class MiniProgramApiRoutes extends ApiRoutes
{
    /**
     * @param LumenRouter|DingoRouter $router
     * */
    public function subRoutes($router)
    {
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->post('/register/user', ['as' => 'user.register.user','uses' => 'WechatAuthController@registerUser']);
        $router->get('/user/info/{openid}', ['as' => 'user.info','uses' => 'WechatAuthController@userInfo']);
    }
}