<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/28
 * Time: 上午10:11
 */

namespace App\Routes;
use Dingo\Api\Routing\Router as DingoRouter;
use Dingo\Api\Routing\Router;
use Laravel\Lumen\Routing\Router as LumenRouter;

class PaymentApiRoutes extends ApiRoutes
{
    /**
     * @param LumenRouter|DingoRouter $router
     * */
    protected function subRoutes($router)
    {
        tap($router, function (Router $router) {
            parent::subRoutes($router); // TODO: Change the autogenerated stub
            $router->post('/ali/aggregate', ['as' => 'aggregate.ali.payment.post', 'uses' => 'AliPaymentController@aggregate']);
            $router->post('/wechat/aggregate', ['as' => 'aggregate.wechat.payment.post', 'uses' => 'WechatPaymentController@aggregate']);
        });
    }
}