<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/1
 * Time: 11:24
 */

namespace App\Routes;


class TestApiRoutes extends ApiRoutes
{
    protected function  subRoutes($router){
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->get('/test/login', ['as' => 'test.login', 'uses' => 'TestController@testLogin']);
    }
}