<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/13
 * Time: 下午12:40
 */
namespace App\Routes;
use Dingo\Api\Routing\Router as DingoRouter;
use Laravel\Lumen\Routing\Router as LumenRouter;
class WebApiRoutes extends ApiRoutes
{
    use CommonApiRoutes;

    /**
     * @param DingoRouter|LumenRouter $router
     * */
    protected function subRoutes($router)
    {
        parent::subRoutes($router); // TODO: Change the autogenerated stub
        $router->group(['middleware' => ['api.auth']], function ($router) {
            $router->get('/users',['as' => 'users.list', 'uses' => 'UsersController@getUsers']);
            $router->get('/user/{id}',['as' => 'user.detail', 'uses' => 'UsersController@getUserDetail']);
            //登录用户信息路由
            $router->get('/self/info', ['as' => 'self.info', 'uses' => 'MySelfController@selfInfo']);
            $router->put('/change/password', ['as' => 'change.password', 'uses' => 'MySelfController@changePassword']);

            $router->post('/shop', ['as' => 'shop.create', 'uses' => 'ShopsController@store']);
            $router->get('/shops', ['as' => 'shop.list', 'uses' => 'ShopsController@getShops']);
            $router->get('/shop/{id}', ['as' => 'shop.detail', 'uses' => 'ShopsController@getShopDetail']);
            $router->put('/shop/{id}', ['as' => 'shop.update', 'uses' => 'ShopsController@update']);
        });
        $router->get('/countries', ['as' => 'country.list', 'uses' => 'CountryController@getCountries']);
        $router->get('/country/{id}', ['as' => 'country.detail', 'uses' => 'CountryController@getCountryDetail']);
        $router->get('/country/{countryId}/provinces', ['as' => 'province.list', 'uses' => 'ProvinceController@getProvinces']);
        $router->get('/province/{id}', ['as' => 'province.detail', 'uses' => 'ProvinceController@getProvinceDetail']);
        $router->get('/country/{countryId}/province/{provinceId}/cities', ['as' => 'city.list', 'uses' => 'CityController@getCities']);
        $router->get('/city/{id}', ['as' => 'city.detail', 'uses' => 'CityController@getCityDetail']);
        $router->get('/country/{countryId}/province/{provinceId}/city/{cityId}/counties', ['as' => 'county.list', 'uses' => 'CountyController@getCounties']);
        $router->get('/county/{id}', ['as' => 'county.detail', 'uses' => 'CountyController@getCountyDetail']);

    }
}