<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/13
 * Time: 下午12:40
 */
namespace App\Routes;
use Dingo\Api\Routing\Router;
class WebRoutes extends Routes
{
    protected function routes(Router $router)
    {
        $router->get('', function (){
            return 'Web API';
        });
        parent::routes($router); // TODO: Change the autogenerated stub
    }
}