<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/13
 * Time: 下午12:40
 */
namespace App\Routes;
use Dingo\Api\Routing\Router;
class WebRoutes extends Routes
{
    use CommonRoutes;

    protected function subRoutes(Router $api)
    {
        parent::subRoutes($api); // TODO: Change the autogenerated stub
        $api->group(['middleware' => ['api.auth']], function () use($api){
            $api->get('/users',['as' => 'users.list', 'uses' => 'UsersController@getUsers']);
            $api->get('/user/{id}',['as' => 'user.detail', 'uses' => 'UsersController@getUserDetail']);

            //登录用户信息路由
            $api->get('/self/info', ['as' => 'self.info', 'uses' => 'MySelfController@selfInfo']);
            $api->put('/change/password', ['as' => 'change.password', 'uses' => 'MySelfController@changePassword']);

            $api->post('/shop', ['as' => 'shop.create', 'uses' => 'ShopsController@store']);
            $api->get('/shops', ['as' => 'shop.list', 'uses' => 'ShopsController@getShops']);
            $api->get('/shop/{id}', ['as' => 'shop.detail', 'uses' => 'ShopsController@getShopDetail']);
            $api->put('/shop/{id}', ['as' => 'shop.update', 'uses' => 'ShopsController@update']);
        });
    }
}