<?php

namespace App\Http\Controllers\Payment;

use App\Entities\Order;
use App\Http\Controllers\Payment\PaymentController as Controller;
use Dingo\Api\Http\Request;
use Dingo\Api\Http\Response;
use Payment\ChargeContext;
use Payment\NotifyContext;

class WechatPaymentController extends Controller
{
    /**
     * 聚合支付
     * @param Request $request
     * @return Response| null
     * @throws
     * */
    public function aggregate(Request $request)
    {
        $_POST['pay_type'] = Order::WECHAT_PAY;
        $order = $this->app->make('order.builder')->handle();
        return $this->preOrder(self::WAP_PAY, $order->id);
    }

    /**
     * 统一下单
     * @param int $id
     * @param string $type
     * @param ChargeContext|null $charge
     * @return Response| null
     * */
    public function preOrder(string $type, int $id, $charge = null)
    {
        $charge = app('payment.wechat.'.$type);
        return parent::preOrder($type, $id, $charge);
    }

    public function notify(string $type = 'wechat', NotifyContext $notify = null)
    {
        $notify = $this->app->make('payment.wechat.notify');
        parent::notify($type, $notify); // TODO: Change the autogenerated stub
    }
}
