<?php

namespace App\Http\Requests\Admin;

use App\Entities\Merchandise;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class MerchandiseCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'categories' => ['required', 'array'],
//            'name' => ['required', 'max:255'],
//            'main_image' => ['required', 'url'],
//            'images' => ['required', 'array'],
//            'preview' => ['required', 'max:256'],
//            'origin_price' => ['required', 'numeric'],
//            'sell_price' => ['required', 'numeric'],
//            'cost_price' => ['numeric'],
//            'factory_price' => ['numeric'],
//            'stock_num' => ['required', 'integer'],
//            'status' => ['required', Rule::in([Merchandise::UP, Merchandise::DOWN])]
        ];
    }

    public function messages()
    {
        return [
            'categories.required' => '分类必填' ,
//            'name.required' => '名称必填',
//            'main_image.required' => '必须填写商品主图',
//            'images.required' => '缺少商品图片列表',
//            'preview.required' => '缺少简介',
//            'origin_price.required' => '缺少原价',
//            'sell_price.required' => '缺少售价',
//            'stock_num.required' => '缺少库存数据',
//            'status.required' => '缺少商品状态'
        ]; // TODO: Change the autogenerated stub
    }
}
