<?php
/**
 * Created by PhpStorm.
 * User: wangzaron
 * Date: 2018/9/10
 * Time: 上午10:51
 */

namespace App\Http\Requests\Admin;


use AlbertCht\Form\FormRequest;

class OpenPlatformAuthCallbackRequest extends FormRequest
{
    public function authorize()
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        // TODO: Implement rules() method.
        return [
            'auth_code' => 'required|string',
            'expires_in' => 'required|integer',
            'token' => 'required|string'
        ];
    }
}