<?php

namespace App\Http\Requests\Admin;

use App\Entities\OrderGift;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class OrderGiftUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'activity_id' => ['required','int'],
            'ticket_id' => ['required','int'],
            'discount' =>['required','string'],
            'cost' =>['required','string'],
            'least_amount' =>['required','string'],
            'score' => ['required','int'],
            'type' => ['required', Rule::in([OrderGift::PAY_FULL, OrderGift::PAY_GIFT])],
        ];
    }

    public function messages()
    {
        return [
            'activity_id.required' => '缺少必填参数activity_id',
            'ticket_id.required' => '缺少必填参数ticket_id',
            'discount.required' => '缺少必填参数discount',
            'cost.required' => '缺少必填参数cost',
            'least_amount.required' => '缺少必填参数least_amount',
            'score.required' => '缺少必填参数score',
            'type.required' => '缺少必填参数type',
            'type.in' => '参数type取值必须为 '.OrderGift::PAY_GIFT.'或'.OrderGift::PAY_FULL,
        ]; // TODO: Change the autogenerated stub
    }
}
