<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/10/17
 * Time: 下午3:53
 */

namespace App\Http\Requests\Admin;


use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'mobile' => ['required', 'mobile', 'not_exist:users,mobile'],
            'password' => ['required']
        ];
    }

    public function messages()
    {
        return [
            'mobile.required' => '请填写注册手机号码',
            'mobile.mobile' => '您填写的手机号码格式错误',
            'mobile.not_exist' => '该手机已被注册，请重新输入',
            'password' => '请输入注册密码'
        ]; // TODO: Change the autogenerated stub
    }
}