<?php

namespace App\Http\Requests\Admin;

use Urameshibr\Requests\FormRequest;

class SetMpConfigRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'app_id' => ['required'],
            'app_name' => ['required'],
            'aes_key'  => ['required'],
            'token' => ['required'],
            'app_secret' => ['required']
        ];
    }

    public function messages()
    {
        return [
            'app_id.required' => '缺少必填参数app_id',
            'app_name.required' => '缺少必填参数app_name',
            'app_secret.required' => '缺少必填参数app_secret',
            'aes_key.required' => '缺少必填参数aes_key',
            'token.required' => '缺少必填参数token'
        ]; // TODO: Change the autogenerated stub
    }
}
