<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/10/17
 * Time: 下午3:44
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Auth\AuthController as Controller;
use App\Http\Requests\Admin\RegisterRequest;
use App\Http\Response\JsonResponse;
use App\Repositories\AdministratorRepository;
use App\Repositories\AppRepository;
use App\Repositories\UserRepository;
use Dingo\Api\Exception\StoreResourceFailedException;
use Dingo\Api\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class AuthController extends Controller {
    use ControllerTrait;

    const RULES = [
        'mobile' => ['required', 'mobile', 'roles:SYS_ADMIN,SUPER_ADMIN,TESTER,DEVELOPER'],
        'password' => ['required', 'regex:' . PASSWORD_PATTERN]
    ];

    const MESSAGES = [
        'mobile.required' => '缺少手机号码',
        'password.required' => '未提交密码',
        'mobile.mobile' => '手机号码格式错误',
        'password.regex' => '密码格式错误',
        'mobile.roles' => '此账号不是管理员'
    ];

    protected  $administratorRepository = null;

    public function __construct(AdministratorRepository $administratorRepository, AppRepository $appRepository, Request $request)
    {
        parent::__construct(app(UserRepository::class));

        $this->administratorRepository = $administratorRepository;

        $this->parseApp($request, $appRepository);
    }

    public function accountInfo() {

    }

    /**
     * @param RegisterRequest $request
     * @return Response
     * */
    public function register(RegisterRequest $request)
    {
        $user = $request->all();

        $user['mobile_company'] = mobileCompany($user['mobile']);

        $user['user_name'] = $user['mobile'];

        $user['password'] = password($user['password'], true);

        $user = $this->administratorRepository->create($user);

        if($user) {
            return $this->response(new JsonResponse([
                'message' => '注册成功'
            ]));
        }else {
            throw new StoreResourceFailedException('注册失败！', null, [], AUTH_REGISTER_FAIL);
        }
    }

    /**
     * @param Request $request
     * @return Response
     * */
    public function authenticate(Request $request)
    {
        return parent::authenticate($request); // TODO: Change the autogenerated stub
    }
}