<?php

namespace App\Http\Controllers\Admin;

use App\Criteria\Admin\SearchRequestCriteria;
use App\Criteria\Admin\TicketCriteria;
use App\Entities\CustomerTicketCard;
use App\Entities\Ticket;
use App\Events\SyncTicketCardInfoEvent;
use App\Http\Controllers\Admin\CardsController as Controller;
use App\Http\Requests\Admin\TicketCreateRequest;
use App\Http\Requests\Admin\TicketUpdateRequest;
use App\Repositories\TicketRepository;
use App\Services\AppManager;
use App\Transformers\TicketItemTransformer;
use App\Transformers\TicketTransformer;
use Dingo\Api\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Event;

class TicketController extends Controller
{
    //
    use ControllerTrait;

    protected $ticketRepository = null;

    public function __construct(TicketRepository $ticketRepository)
    {
        $this->ticketRepository = $ticketRepository;
        parent::__construct($ticketRepository);
    }


    /**
     *创建现金/折扣券
     * @param TicketCreateRequest $request
     * @return \Dingo\Api\Http\Response
     * @throws \Exception
     */
    public function store(TicketCreateRequest $request)
    {
        $ticket = $request->input('ticket_info');
        if ($request->input('ticket_type', Ticket::CASH) === Ticket::DISCOUNT) {
            $ticket['least_cost'] = null;
        }
        if (isset($ticket['least_cost']) && $ticket['least_cost'] !== null) {
            $ticket['least_cost'] = (float)$ticket['least_cost'];
        }

        if (isset($ticket['reduce_cost']) && $ticket['reduce_cost'] !== null) {
            $ticket['reduce_cost'] = (float)$ticket['reduce_cost'];
        }

        if (isset($ticket['discount']) && $ticket['discount'] !== null) {
            $ticket['discount'] = (float)$ticket['discount'];
        }

        $request->merge([
            'card_info' => $ticket,
            'platform' => $request->input('platform', OWNER_TICKET),
            'card_type' => $request->input('ticket_type', Ticket::CASH),
            'begin_at' => Carbon::createFromTimeString($request->input('begin_at', Carbon::now()->format('Y-m-d H:i:s'))),
            'end_at' => $request->input('end_at', null) ? Carbon::createFromTimeString($request->input('end_at')) : null
        ]);
        $ticket = parent::storeCard($request);

        if ($request->input('sync', false)) {
            $ticket->exists = true;
            Event::fire(new SyncTicketCardInfoEvent($ticket, null, app('wechat')->officeAccount()));
        }
        return $this->response()->item($ticket, new TicketTransformer());
    }

    /**
     * 获取优惠券列表
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->ticketRepository->pushCriteria(app(TicketCriteria::class));
        $this->ticketRepository->pushCriteria(app(SearchRequestCriteria::class));
        $this->ticketRepository->withCount([
            'customerTickets as used_count' => function (Builder $query) {
                return $query->whereNotNull('customer_id')->where('status', CustomerTicketCard::STATUS_USE);
            }
        ]);
        $tickets = parent::index(); // TODO: Change the autogenerated stub

        return $this->response()->paginator($tickets, new TicketItemTransformer());
    }

    /**
     *
     * @param TicketUpdateRequest $request
     * @param $id
     * @return \Dingo\Api\Http\Response
     * @throws \Exception
     */
    public function update(TicketUpdateRequest $request, $id)
    {
        $ticket = parent::updateCard($request, $id); // TODO: Change the autogenerated stub
        if ($request->input('sync', false)) {
            $ticket->exists = true;
            Event::fire(new SyncTicketCardInfoEvent($ticket, $ticket->cardInfo, app('wechat')->officeAccount()));
        }

        return $this->response()->item($ticket, new TicketTransformer());
    }

    /**
     * @param int $id
     * @return Response
     * @throws
     * */
    public function unavailable(int $id)
    {
        $result = $this->repository
            ->update(['status' => Ticket::UNAVAILABLE], $id);

        if ($result) {
            $result = app('wechat')
                ->officeAccount()->card
                ->reduceStock($result->cardId, $result->cardInfo['base_info']['sku']['quantity']);

            if ($result['errcode'] !== 0) {
                $this->response()->error('同步失败', HTTP_STATUS_NOT_MODIFIED);
            } else {
                return $this->response(new JsonResponse(['message' => '设置成功，卡券已经失效']));
            }
        } else {
            $this->response()->error('设置失败', HTTP_STATUS_NOT_MODIFIED);
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Dingo\Api\Http\Response
     */
    public function show($id)
    {
        /** @var Ticket $id */
        $ticket = parent::show($id);
        return $this->response()->item($ticket, new TicketTransformer());
    }

    /**
     * 普通链接二维码
     * Ticket normal promote qrCode.
     *
     * @param Request $request
     * @param int $ticketId
     * @return \Dingo\Api\Http\Response
     */
    public function promoteQRCode(Request $request, int $ticketId)
    {
        $url = buildUrl('web.wxMp', '/ticket/receive/{ticketId}', ['ticketId' => $ticketId]);
        $code = app('qrcode')->format('png')->margin(2)->size($request->input('size', 128))->generate($url);
        return $this->response()->created()->setContent($code)->header('Content-Type', 'image/png');
    }

    /**
     * 小程序码
     * @param Request $request
     * @param int $ticketId
     */
    public function promoteMiniCode(Request $request, int $ticketId)
    {
        $appId = app(AppManager::class)->getAppId();

        /** @var Ticket $ticket */
        $ticket = $this->ticketRepository->scopeQuery(function (Ticket $card) use ($appId) {
            return $card->whereAppId($appId);
        })->find($ticketId);

        $response = $this->ticketRepository->getPromoteMiniCode($ticket);

        return $response;
    }
}
