<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/5
 * Time: 0:49
 */

namespace App\Repositories;

use App\Entities\MpUser;
use App\Repositories\Traits\Destruct;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Services\AppManager;

class MpUserRepositoryEloquent extends BaseRepository implements MpUserRepository
{

    use Destruct;
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return MpUser::class;
    }



    /**
     * Boot up the repository, pushing criteria
     * @throws
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function create(array $attributes)
    {
        if($attributes['gender'] == 0){
            $attributes['gender'] = 'UNKNOWN';
        }elseif ($attributes['gender']==1){
            $attributes['gender'] = 'MALE';
        }elseif ($attributes['gender'] == 1){
            $attributes['gender'] = 'FEMALE';
        }
        $currentApp = app(AppManager::class)->currentApp;
        $mpUser['platform_app_id'] = $currentApp['mini_app_id'];
        $mpUser['union_id'] = $attributes['unionId'];
        $mpUser['platform_open_id'] = $attributes['openId'];
        $mpUser['session_key'] = $attributes['session_key'];
        $mpUser['avatar'] = $attributes['avatarUrl'];
        $mpUser['nickname'] = $attributes['nickName'];
        $mpUser['country'] = $attributes['country'];
        $mpUser['province'] = $attributes['province'];
        $mpUser['city'] = $attributes['city'];
        $mpUser['sex'] = $attributes['gender'];
        $mpUser['app_id'] = $attributes['app_id'];
        return parent::create($mpUser); // TODO: Change the autogenerated stub
    }

    }