<?php

namespace App\Repositories;

use App\Validators\Admin\ShopsValidator;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Entities\Shop;

/**
 * Class ShopRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class ShopRepositoryEloquent extends BaseRepository implements ShopRepository
{
    protected $fieldSearchable = [
        'country.name',
        'province.name',
        'city.name',
        'county.name'
    ];
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Shop::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     * @throws
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
//        $this->model->addObservableEvents([
//            'creating' => function (Shop $shop) {
//
//            },
//            'created' => function (Shop $shop) {
//
//            },
//            'updated' => function (Shop $shop) {
//
//            }
//        ]);
    }

    public function validator()
    {
        return ShopsValidator::class; // TODO: Change the autogenerated stub
    }

}
